### ISSUE TITLE
How to use gpu accelerate speed

### ISSUE THREAD

**Issue by KakaVlasic** [JanaLipkova/s3#2]
Hi! Thanks sharing code, I just wanna know how to use gpu accelerate speed in batch processing?

**Comment by JanaLipkova** [comment]
Hi Kaka, 
thank you for the question. The segmentation is based purely on image registration, there is no deep learning nor pytorch, so do software doesn't support GPU per se. One would need to replace the registration libraries by their GPU counterparts, but I am not sure if all have it. So short answer, I am sorry there is no GPU support.
